package com.athlon.identityservice.rewards.enums;

public enum CreditRuleKey {
    REFERRAL_SIGNUP_REFERRER,
    REFERRAL_SIGNUP_REFEREE,
    TOURNAMENT_CONDUCTED_ORGANIZER,
    TOURNAMENT_PARTICIPATION_PLAYER,
    ORGANIZER_SUBSCRIPTION_CREDIT_COST,
    ORGANIZER_FREE_TOURNAMENT_COST
}
