import type { AthlonTheme } from './theme-types';
import { SEMANTIC_COLORS } from './theme-constants';

const SEM = SEMANTIC_COLORS;

// Base dark foundation colors - Modern Deep Slate Navy with high daylight contrast
const DARK_BG = '#0A0F1D';
const DARK_BG_SEC = '#0E1426';
const DARK_SURFACE = '#11182B';
const DARK_SURFACE_HOVER = '#1A243D';
const DARK_SURFACE_ACTIVE = '#212F4E';
const DARK_CARD = '#141C30';
const DARK_CARD_HOVER = '#1C2742';
const DARK_CARD_ELEVATED = '#222F4F';
const DARK_BORDER = '#202D47';
const DARK_BORDER_STRONG = '#2D3F63';
const DARK_BORDER_SUBTLE = '#18233A';
const DARK_INPUT = '#0D1322';
const DARK_INPUT_BORDER = '#202D47';
const DARK_NAV = '#0E1527';
const DARK_PANEL = '#11182B';

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON GREEN — Fresh Sports / Deep Dark + Green Accent
// ─────────────────────────────────────────────────────────────────────────────
const algae: AthlonTheme = {
  key: 'algae',
  name: 'Athlon Green',
  description: 'Fresh, natural, sports-forward dark green experience.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#54AC68',
    primaryHover: '#68BE7B',
    primaryActive: '#3E9050',
    primaryLight: '#76BD86',
    primaryDark: '#32673E',
    primarySoft: 'rgba(84,172,104,0.08)',
    primaryMuted: 'rgba(84,172,104,0.04)',
    primaryGlow: 'rgba(84,172,104,0.18)',
    primaryForeground: '#050807',
    text: '#F8FAFC',
    textSecondary: '#A4B3C6',
    textMuted: '#748398',
    textDisabled: '#4A576C',
    icon: '#98A7BE',
    iconMuted: '#66768E',
    iconActive: '#54AC68',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#54AC68',
    navigationBackground: DARK_NAV,
    navigationActive: '#54AC68',
    navigationHover: 'rgba(84,172,104,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#0B1B12',
    gradientMiddle: '#143020',
    gradientEnd: '#54AC68',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(84,172,104,0.15)',
    chartPrimary: '#54AC68',
    chartSecondary: '#3A7A4A',
    chartTertiary: '#A3D9B1',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON PULSE — Futuristic Electric / Obsidian-Cyan Accent
// ─────────────────────────────────────────────────────────────────────────────
const pulse: AthlonTheme = {
  key: 'pulse',
  name: 'Athlon Pulse',
  description: 'Electric, futuristic technology aesthetic.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#04D9FF',
    primaryHover: '#26E2FF',
    primaryActive: '#02B8D9',
    primaryLight: '#65EAFF',
    primaryDark: '#0290A8',
    primarySoft: 'rgba(4,217,255,0.08)',
    primaryMuted: 'rgba(4,217,255,0.04)',
    primaryGlow: 'rgba(4,217,255,0.18)',
    primaryForeground: '#020D15',
    text: '#EDF4F8',
    textSecondary: '#94A4B4',
    textMuted: '#5E6D7E',
    textDisabled: '#38424E',
    icon: '#8A96A4',
    iconMuted: '#525D6B',
    iconActive: '#04D9FF',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#04D9FF',
    navigationBackground: DARK_NAV,
    navigationActive: '#04D9FF',
    navigationHover: 'rgba(4,217,255,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#061624',
    gradientMiddle: '#0A253C',
    gradientEnd: '#04D9FF',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(4,217,255,0.15)',
    chartPrimary: '#04D9FF',
    chartSecondary: '#027FA0',
    chartTertiary: '#7FE8F8',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON RUSH — Youthful Adrenaline / Crimson Accent
// ─────────────────────────────────────────────────────────────────────────────
const rush: AthlonTheme = {
  key: 'rush',
  name: 'Athlon Rush',
  description: 'Bold youthful energy with crimson intensity.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#FE4164',
    primaryHover: '#FF617F',
    primaryActive: '#DE2550',
    primaryLight: '#FF8CA3',
    primaryDark: '#B01438',
    primarySoft: 'rgba(254,65,100,0.08)',
    primaryMuted: 'rgba(254,65,100,0.04)',
    primaryGlow: 'rgba(254,65,100,0.18)',
    primaryForeground: '#0C0205',
    text: '#F7EEF0',
    textSecondary: '#A89A9E',
    textMuted: '#6E6165',
    textDisabled: '#423A3D',
    icon: '#998D91',
    iconMuted: '#5F5458',
    iconActive: '#FE4164',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#FE4164',
    navigationBackground: DARK_NAV,
    navigationActive: '#FE4164',
    navigationHover: 'rgba(254,65,100,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#1E0A12',
    gradientMiddle: '#340E1E',
    gradientEnd: '#FE4164',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(254,65,100,0.15)',
    chartPrimary: '#FE4164',
    chartSecondary: '#9C1A3C',
    chartTertiary: '#FFAABB',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON FIRE — Competitive Intensity / Ember Accent
// ─────────────────────────────────────────────────────────────────────────────
const fire: AthlonTheme = {
  key: 'fire',
  name: 'Athlon Fire',
  description: 'High-intensity competitive ember dark theme.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#FF4500',
    primaryHover: '#FF6025',
    primaryActive: '#DD3300',
    primaryLight: '#FF8050',
    primaryDark: '#B02A00',
    primarySoft: 'rgba(255,69,0,0.08)',
    primaryMuted: 'rgba(255,69,0,0.04)',
    primaryGlow: 'rgba(255,69,0,0.18)',
    primaryForeground: '#0C0402',
    text: '#F8EFEA',
    textSecondary: '#A89D96',
    textMuted: '#6F645D',
    textDisabled: '#433C37',
    icon: '#998F88',
    iconMuted: '#605750',
    iconActive: '#FF4500',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#FF4500',
    navigationBackground: DARK_NAV,
    navigationActive: '#FF4500',
    navigationHover: 'rgba(255,69,0,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#1E0C06',
    gradientMiddle: '#34140A',
    gradientEnd: '#FF4500',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(255,69,0,0.15)',
    chartPrimary: '#FF4500',
    chartSecondary: '#B03000',
    chartTertiary: '#FFAA88',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON WINE — Premium Luxury / Burgundy Accent
// ─────────────────────────────────────────────────────────────────────────────
const wine: AthlonTheme = {
  key: 'wine',
  name: 'Athlon Wine',
  description: 'Premium mature elegance with deep burgundy.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#A83279',
    primaryHover: '#C044A0',
    primaryActive: '#8A1F60',
    primaryLight: '#D47DB0',
    primaryDark: '#601D4A',
    primarySoft: 'rgba(168,50,121,0.08)',
    primaryMuted: 'rgba(168,50,121,0.04)',
    primaryGlow: 'rgba(168,50,121,0.18)',
    primaryForeground: '#FCEDF8',
    text: '#F7EFF6',
    textSecondary: '#A79CA6',
    textMuted: '#6D636C',
    textDisabled: '#413B41',
    icon: '#988E97',
    iconMuted: '#5F565E',
    iconActive: '#A83279',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#A83279',
    navigationBackground: DARK_NAV,
    navigationActive: '#A83279',
    navigationHover: 'rgba(168,50,121,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#1A0B15',
    gradientMiddle: '#2E1125',
    gradientEnd: '#A83279',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(168,50,121,0.15)',
    chartPrimary: '#A83279',
    chartSecondary: '#601D4A',
    chartTertiary: '#E0A0CC',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON BERRY — Bold Modern Lifestyle / Berry Accent
// ─────────────────────────────────────────────────────────────────────────────
const berry: AthlonTheme = {
  key: 'berry',
  name: 'Athlon Berry',
  description: 'Bold modern lifestyle with deep berry accents.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#AD3D5E',
    primaryHover: '#C4546D',
    primaryActive: '#8E2245',
    primaryLight: '#D27F87',
    primaryDark: '#6E1536',
    primarySoft: 'rgba(173,61,94,0.08)',
    primaryMuted: 'rgba(173,61,94,0.04)',
    primaryGlow: 'rgba(173,61,94,0.18)',
    primaryForeground: '#FCEEF1',
    text: '#F7EEF1',
    textSecondary: '#A79BA0',
    textMuted: '#6D6267',
    textDisabled: '#413A3D',
    icon: '#988E93',
    iconMuted: '#5F555A',
    iconActive: '#AD3D5E',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#AD3D5E',
    navigationBackground: DARK_NAV,
    navigationActive: '#AD3D5E',
    navigationHover: 'rgba(173,61,94,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#1B0B12',
    gradientMiddle: '#301120',
    gradientEnd: '#AD3D5E',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(173,61,94,0.15)',
    chartPrimary: '#AD3D5E',
    chartSecondary: '#6E1536',
    chartTertiary: '#E39E9C',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON SLATE — Professional Corporate / Cool Slate Accent
// ─────────────────────────────────────────────────────────────────────────────
const slate: AthlonTheme = {
  key: 'slate',
  name: 'Athlon Slate',
  description: 'Professional calm corporate blue-gray experience.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#8283AD',
    primaryHover: '#9A9BC5',
    primaryActive: '#6566A0',
    primaryLight: '#A0A1C2',
    primaryDark: '#504F80',
    primarySoft: 'rgba(130,131,173,0.08)',
    primaryMuted: 'rgba(130,131,173,0.04)',
    primaryGlow: 'rgba(130,131,173,0.18)',
    primaryForeground: '#05060B',
    text: '#EEF0F7',
    textSecondary: '#9BA0B2',
    textMuted: '#62677A',
    textDisabled: '#3B3E4C',
    icon: '#8E92A2',
    iconMuted: '#555866',
    iconActive: '#8283AD',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#8283AD',
    navigationBackground: DARK_NAV,
    navigationActive: '#8283AD',
    navigationHover: 'rgba(130,131,173,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#111326',
    gradientMiddle: '#1D203E',
    gradientEnd: '#8283AD',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(130,131,173,0.15)',
    chartPrimary: '#8283AD',
    chartSecondary: '#504F80',
    chartTertiary: '#BEC0D6',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// ATHLON FOREST — Deep Power / Pine Accent
// ─────────────────────────────────────────────────────────────────────────────
const forest: AthlonTheme = {
  key: 'forest',
  name: 'Athlon Forest',
  description: 'Deep forest, earthy and powerful dark natural theme.',
  colors: {
    background: DARK_BG,
    backgroundSecondary: DARK_BG_SEC,
    surface: DARK_SURFACE,
    surfaceHover: DARK_SURFACE_HOVER,
    surfaceActive: DARK_SURFACE_ACTIVE,
    card: DARK_CARD,
    cardHover: DARK_CARD_HOVER,
    cardElevated: DARK_CARD_ELEVATED,
    border: DARK_BORDER,
    borderStrong: DARK_BORDER_STRONG,
    borderSubtle: DARK_BORDER_SUBTLE,
    primary: '#3A7A3E',
    primaryHover: '#4A9A4E',
    primaryActive: '#2C5E30',
    primaryLight: '#68A86C',
    primaryDark: '#1B4020',
    primarySoft: 'rgba(58,122,62,0.08)',
    primaryMuted: 'rgba(58,122,62,0.04)',
    primaryGlow: 'rgba(58,122,62,0.18)',
    primaryForeground: '#F0F7F0',
    text: '#EFF5EF',
    textSecondary: '#9AA79A',
    textMuted: '#627062',
    textDisabled: '#3B443B',
    icon: '#8A968A',
    iconMuted: '#535F53',
    iconActive: '#3A7A3E',
    inputBackground: DARK_INPUT,
    inputBorder: DARK_INPUT_BORDER,
    inputFocus: '#3A7A3E',
    navigationBackground: DARK_NAV,
    navigationActive: '#3A7A3E',
    navigationHover: 'rgba(58,122,62,0.06)',
    headerBackground: DARK_NAV,
    sidebarBackground: DARK_NAV,
    panelBackground: DARK_PANEL,
    gradientStart: '#0A1A0D',
    gradientMiddle: '#132E18',
    gradientEnd: '#3A7A3E',
    shadow: 'rgba(0,0,0,0.60)',
    glow: 'rgba(58,122,62,0.15)',
    chartPrimary: '#3A7A3E',
    chartSecondary: '#826945',
    chartTertiary: '#8ABD8C',
  },
  semantic: SEM,
};

// ─────────────────────────────────────────────────────────────────────────────
// REGISTRY
// ─────────────────────────────────────────────────────────────────────────────
export const ATHLON_THEMES: Record<string, AthlonTheme> = {
  algae,
  pulse,
  rush,
  fire,
  wine,
  berry,
  slate,
  forest,
};

export const THEME_ORDER: AthlonTheme['key'][] = [
  'algae',
  'pulse',
  'rush',
  'fire',
  'wine',
  'berry',
  'slate',
  'forest',
];

export const THEME_VIDEOS: Record<string, string> = {
  fire: '/athlon-fire.mp4',
  forest: '/athlon-forest.mp4',
  pulse: '/athlon-pulse.mp4',
  slate: '/athlon-slate.mp4',
  wine: '/athlon-wine.mp4',
};

export const DEFAULT_THEME_VIDEO = '/athlon-background.mp4';

export function getThemeVideo(themeKey?: string | null): string {
  if (!themeKey) return DEFAULT_THEME_VIDEO;
  return THEME_VIDEOS[themeKey] || DEFAULT_THEME_VIDEO;
}

