spring.application.name=IDENTITYSERVICE
server.port=5052

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/athlon
spring.datasource.username=postgres
spring.datasource.password=19sep@1990

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.level.root=INFO
logging.level.com.athlon.auth=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

athlon.player.photo.upload.directory=./uploads

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
