spring.application.name=IDENTITYSERVICE
server.port=5052

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ls-7c159dddf5c32632237aa1d1862c492ed00d6fae.c1uwq0k8g2rc.ap-south-1.rds.amazonaws.com:5432/athlon?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=dbmasteruser
spring.datasource.password=Aws#Db&2026


# Pool Name
spring.datasource.hikari.pool-name=IdentityServicePool

# Pool Size
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Timeouts
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000

# Lifetime (Must be lower than PostgreSQL timeout)
spring.datasource.hikari.max-lifetime=1500000

# Keep connections alive
spring.datasource.hikari.keepalive-time=120000

# Leak Detection (Development)
spring.datasource.hikari.leak-detection-threshold=60000

# Auto Commit
spring.datasource.hikari.auto-commit=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

athlo.gateway.url=http://localhost:5050

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=

athlon.user.photo.upload.directory=C:\\Users\\neoni\\Desktop\\Athlon\\User

athlon.org.upload.directory=C:\\Users\\neoni\\Desktop\\Athlon\\Organization